// Budget & Benchmark types
export interface Benchmark {
  cpc: number
  ctr: number
  convRate: number
}

export interface BudgetMetrics {
  clicks: number
  conversions: number
  costPerConversion: number
  impressions: number
}

// Copy Analysis types
export interface CopyAnalysisResult {
  score: number
  suggestions: string[]
  variants: string[]
}

// UTM Builder types
export interface UTMParams {
  url: string
  source: string
  medium: string
  campaign: string
  term?: string
  content?: string
}

export interface UTMPreset {
  name: string
  params: {
    source: string
    medium: string
    campaign: string
    term: string
    content: string
  }
}

// Countdown Timer types
export interface CountdownPreset {
  name: string
  color: string
  accent: string
}

// Analytics types
export interface AnalyticsEvent {
  eventType: string
  toolSlug?: string
  context?: string
  url?: string
  utm?: {
    utm_source?: string
    utm_medium?: string
    utm_campaign?: string
    utm_term?: string
    utm_content?: string
  }
  metadata?: Record<string, unknown>
}

export interface ContactFormData {
  name: string
  email: string
  topic?: string
  message: string
}

export interface CaseStudySubmissionData {
  name: string
  email: string
  brand: string
  category?: string
  url?: string
  summary?: string
  metrics?: string
  tools?: string
}

export interface CommentData {
  contentType: string
  slug: string
  name: string
  email: string
  message: string
}

export interface SubscribeData {
  email: string
  name?: string
  leadMagnet?: string
  source?: string
}

// API Response types
export interface ApiSuccessResponse<T = unknown> {
  ok: true
  data?: T
  message?: string
}

export interface ApiErrorResponse {
  ok: false
  error: string
  statusCode?: number
}

export type ApiResponse<T = unknown> = ApiSuccessResponse<T> | ApiErrorResponse

// D1 Database types
export type D1Row = Record<string, unknown>

export interface D1Statement<T = D1Row> {
  bind: (...args: unknown[]) => D1Statement<T>
  run: () => Promise<unknown>
  all: () => Promise<{ results: T[] }>
}

export interface D1Database {
  prepare: <T = D1Row>(query: string) => D1Statement<T>
  exec: (query: string) => Promise<unknown>
}

// Payload CMS types (re-exported from payload-types)
// These types are auto-generated by Payload CMS
export type { Tool, Post, CaseStudy } from '@/payload-types'
